### PR TITLE
jenkins file

### PR DESCRIPTION
**Pull request by jburel**
add Jenkins file for CI

### CODE REVIEW

**Comment by joshmoore** [comment]
Files match those in omero-insight (master) barring the one rename:

```
/tmp $ grep -E "(insight|matlab)" omero-{insight,matlab}/Jenkins*
omero-insight/Jenkinsfile.merge:        BASE_REPO = 'omero-insight.git'
omero-matlab/Jenkinsfile.merge:        BASE_REPO = 'omero-matlab.git'
```

:+1: There's still a general question of whether or not some of this cut-n-paste logic can't be centralized, but happy to defer that another round.

Do you want to test applying these files to west-ci before merging?

**Comment by jburel** [comment]
I do not think "west" is hooked to matlab yet.

**Comment by joshmoore** [comment]
Neither of the Jenkinsfiles actually invoke `MATLAB`, do they? i.e. it would be more about creating the artifacts (and marking duplicates on PRs, etc).

**Comment by jburel** [comment]
https://github.com/openmicroscopy/devspace/pull/127/commits/14536de6a916775e37e13ee2b4dd8eb503418f0e will not work if we do not have jenkins file

**Comment by joshmoore** [comment]
Job now in place in south and green while pointing at this branch. Merging to continue with build.

**Pull request merged**
